=== ankit-Keshari-Nitor/local-pem20/pem-api/pem-common/src/main/resources/Json_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"schemaVersion": {
			"type": "number"
		},
		"process": {
			"type": "object",
			"properties": {
				"nodes": {
					"type": "array",
					"items": {"$ref": "#/definitions/Node"}
				},
				"connectors": {
					"type": "array",
					"items": {"$ref": "#/definitions/Connector"}
				},
				"contextData": {
					"type": "string"
				}
			},
			"required": ["nodes", "connectors"]
		}
	},
	"definitions": {
		"Node": {
			"type": "object",
			"properties": {
				"id": {
					"type": "string",
					"pattern": "^[a-zA-Z0-9_-]+$"
				},
				"name": {
					"type": "string"
				},
				"type": {
					"type": "string",
					"enum": ["START", "END", "FORM", "CONNECTORS", "API", "XSLT", "GATEWAY", "PARTNER", "SYSTEM", "SPONSOR", "CALL_ACTIVITY"]
				},
				"userKeys": {
					"type": "string"
				},
				"roleKeys": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"form": {
					"type": "string",
					"contentMediaType": "application/json",
					"contentEncoding": "utf-8"
				},
				"targetActivity": {
					"type": "string"
				},
				"inVariables": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"source": {
								"type": "string"
							},
							"target": {
								"type": "string"
							}
						},
						"required": ["source", "target"]
					}
				},
				"outVariables": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"source": {
								"type": "string"
							},
							"target": {
								"type": "string"
							}
						},
						"required": ["source", "target"]
					}
				},
				"api": {
					"type": "object",
					"properties": {
						"apiConfiguration": {
							"type": "string"
						},
						"url": {
							"type": "string"
						},
						"method": {
							"type": "string",
							"enum": ["GET", "POST", "PUT", "DELETE", "PATCH"]
						},
						"requestContentType": {
							"type": "string"
						},
						"responseContentType": {
							"type": "string"
						},
						"file": {
							"type": "string"
						},
						"requestHeaders": {
							"type": "string",
							"contentMediaType": "application/json",
							"contentEncoding": "utf-8"
						},
						"request": {
							"type": "string",
							"contentEncoding": "utf-8"
						},
						"sampleResponse": {
							"type": "string",
							"contentMediaType": "application/json",
							"contentEncoding": "utf-8"
						},
						"response": {
							"type": "string",
							"contentMediaType": "application/json",
							"contentEncoding": "utf-8"
						}
					},
					"required": ["apiConfiguration", "url", "method"]
				},
				"xslt": {
					"type": "object",
					"properties": {
						"input": {
							"type": "string"
						},
						"xslt": {
							"type": "string"
						},
						"sampleOutput": {
							"type": "string"
						},
						"output": {
							"type": "string"
						}
					},
					"required": ["input", "xslt", "sampleOutput", "output"]
				},
				"gatewayType": {
					"type": "string"
				},
				"nodes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Node"
					}
				},
				"connectors": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Connector"
					}
				},
				"estimateDays": {
					"type": "number"
				},
				"showToPartner": {
					"type": "boolean"
				},
				"contextData": {
					"type": "string"
				},
				"diagram": {
					"type": "object",
					"properties": {
						"x": {
							"type": "number"
						},
						"y": {
							"type": "number"
						}
					},
					"required": [
						"x",
						"y"
					]
				}
			},
			"required": ["id", "name", "type"],
			"oneOf": [
				{
					"properties": {
						"type": {
							"const": "START"
						}
					}
				},
				{
					"properties": {
						"type": {
							"const": "END"
						}
					}
				},
				{
					"properties": {
						"type": {
							"const" : "PARTNER"
						}
					},
					"required": ["nodes", "connectors"]
				},
				{
					"properties": {
						"type": {
							"const" : "SPONSOR"
						}
					},
					"required": ["nodes", "connectors"]
				},
				{
					"properties": {
						"type": {
							"const" : "SYSTEM"
						}
					},
					"required": ["nodes", "connectors"]
				},
				{
					"properties": {
						"type": {
							"const": "FORM"
						}
					},
					"required": ["form"]
				},
				{
					"properties": {
						"type": {
							"const": "CONNECTORS"
						}
					}
				},
				{
					"properties": {
						"type": {
							"const": "CALL_ACTIVITY"
						}
					}
				},
				{
					"properties": {
						"type": {
							"const": "API"
						}
					}
				},
				{
					"properties": {
						"type": {
							"const": "XSLT"
						}
					}
				},
				{
					"properties": {
						"type": {
							"const": "GATEWAY"
						}
					}
				}
			]
		},
		"Connector": {
			"type": "object",
			"properties": {
				"source": {
					"type": "string"
				},
				"target": {
					"type": "string"
				},
				"condition": {
					"type": "string"
				},
				"diagram": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"x": {
								"type": "number"
							},
							"y": {
								"type": "number"
							}
						}
					}
				}
			},
			"required": ["source", "target"]
		}
	},
	"required": ["name", "description", "schemaVersion", "process"]
}

=== ankit-Keshari-Nitor/local-pem20/pem-api/pem-services/src/test/resources/user_input_sample.json
{
  "name": "Pem Definitions 1",
  "description": "This is definitions 1",
  "schemaVersion": 5.0,
  "process": {
    "nodes": [
      {
        "id": "StartNode_1",
        "type": "START",
        "name": "Start",
        "diagram": {
          "x": 200,
          "y": 200
        }
      },
      {
        "id": "EndNode_1",
        "type": "END",
        "name": "End",
        "diagram": {
          "x": 2500,
          "y": 200
        }
      },
      {
        "id": "SubProcess_1",
        "type": "PARTNER",
        "name": "My Process To call API",
        "description": "This process describes the order fulfilment workflow.",
        "userKeys": "user1,user2,user3",
        "roleKeys": "group1,group2",
        "estimateDays": 10,
        "nodes": [
          {
            "id": "SubStartNode_1",
            "type": "START",
            "name": "Start",
            "diagram": {
              "x": 300,
              "y": 1000
            }
          },
          {
            "id": "SubProcess_1_FormNode_1",
            "type": "FORM",
            "name": "User Task Node",
            "description": "description of form",
            "loop": {
              "loopDataInput": "orderCollection",
              "dataItem": "order",
              "completionCondition":"${orderCollection/order > 0.5}"
            },
            "form": "{\"fields\":[{\"id\":\"1f161396-681a-4ae8-b16f-4f4e4ed282ad\",\"type\":\"textinput\",\"labelText\":\"Email\",\"helperText\":\"Enter email\",\"min\":{\"value\":\"3\",\"message\":\"value should be min 3 char\"},\"max\":{\"value\":\"5\",\"message\":\"value should be max 5 char\"},\"isRequired\":{\"value\":true,\"message\":\"isRequired\"}},{\"id\":\"682127c1-f894-488b-97db-5d06bf8dff89\",\"type\":\"textarea\",\"labelText\":\"TextArea\"},{\"id\":\"1488e97a-975d-4822-b223-f0b0fccf6698\",\"type\":\"select\",\"labelText\":\"Select Filed\"},{\"id\":\"7450017e-e15a-4278-86fa-bb00c40069b5\",\"type\":\"checkbox\",\"labelText\":\"Check Box\"},{\"id\":\"a6bcd0f9-842c-4f6f-88f1-f232c2e59a30\",\"type\":\"radio\",\"labelText\":\"Radio\"},{\"id\":\"9431f756-10c0-4ca5-bab1-3ba27d33c0c3\",\"type\":\"toggle\",\"labelText\":\"Toggler\"},{\"id\":\"3b6ed547-f460-4ed7-9cc9-1c47f64e39e7\",\"type\":\"link\",\"labelText\":\"Link\"},{\"id\":\"ed3f7b49-0265-4fbe-8d4a-6be0a9775922\",\"type\":\"datepicker\",\"labelText\":\"Date Picker\"},{\"id\":\"29e61a98-968d-4303-b777-0959927aefe9\",\"type\":\"tab\",\"children\":[{\"id\":\"43969e1c-1490-47d8-b767-86c89bce91b3\",\"tabTitle\":\"Tab-1\",\"children\":[{\"id\":\"6baf6df7-9a83-4ead-be65-4711f6a4f887\",\"type\":\"radio\",\"labelText\":\"Radio Button\"}]},{\"id\":\"f68f60d9-4538-4047-8343-504a927c8a66\",\"tabTitle\":\"tab-2\",\"children\":[{\"id\":\"43989c6a-1e8c-4e40-b02b-743f6e0d3533\",\"type\":\"textarea\",\"labelText\":\"Text Area\"}]}]},{\"id\":\"6d13daa4-da42-4d16-851d-2df2b00fc8af\",\"type\":\"button\",\"labelText\":\"Submit\"}]}",
            "diagram": {
              "x": 700,
              "y": 1000
            }
          },
          {
            "id": "SubProcess_1_apiNode",
            "type": "API",
            "name": "Partner API Node",
            "description": "apiNode-Task to Call user list.",
            "loop": {
              "loopCardinality": 5
            },
            "api": {
              "apiConfiguration": "apiConfiguration",
              "url": "https://jira.com/browse/PEM-27076",
              "method": "GET",
              "requestContentType": "JSON",
              "responseContentType": "JSON",
              "file": "file object",
              "requestHeaders": "[{\"key\":\"value\"}]",
              "request": "{\"name\":\"test_name\"}",
              "sampleResponse": "{\"name\":\"activiti\",\"application\":\"pem\",\"sampleResponse\":\"sample response object\"}",
              "response": "{\"name\":\"test_name\"}"
            },
            "diagram": {
              "x": 1200,
              "y": 1000
            }
          },
          {
            "id": "SubProcess_1_FormNode_2",
            "type": "FORM",
            "name": "User Task Node 2",
            "description": "description of form",
            "form": "{\"fields\":[{\"id\":\"1f161396-681a-4ae8-b16f-4f4e4ed282ad\",\"type\":\"textinput\",\"labelText\":\"Email\",\"helperText\":\"Enter email\",\"min\":{\"value\":\"3\",\"message\":\"value should be min 3 char\"},\"max\":{\"value\":\"5\",\"message\":\"value should be max 5 char\"},\"isRequired\":{\"value\":true,\"message\":\"isRequired\"}},{\"id\":\"682127c1-f894-488b-97db-5d06bf8dff89\",\"type\":\"textarea\",\"labelText\":\"TextArea\"},{\"id\":\"1488e97a-975d-4822-b223-f0b0fccf6698\",\"type\":\"select\",\"labelText\":\"Select Filed\"},{\"id\":\"7450017e-e15a-4278-86fa-bb00c40069b5\",\"type\":\"checkbox\",\"labelText\":\"Check Box\"},{\"id\":\"a6bcd0f9-842c-4f6f-88f1-f232c2e59a30\",\"type\":\"radio\",\"labelText\":\"Radio\"},{\"id\":\"9431f756-10c0-4ca5-bab1-3ba27d33c0c3\",\"type\":\"toggle\",\"labelText\":\"Toggler\"},{\"id\":\"3b6ed547-f460-4ed7-9cc9-1c47f64e39e7\",\"type\":\"link\",\"labelText\":\"Link\"},{\"id\":\"ed3f7b49-0265-4fbe-8d4a-6be0a9775922\",\"type\":\"datepicker\",\"labelText\":\"Date Picker\"},{\"id\":\"29e61a98-968d-4303-b777-0959927aefe9\",\"type\":\"tab\",\"children\":[{\"id\":\"43969e1c-1490-47d8-b767-86c89bce91b3\",\"tabTitle\":\"Tab-1\",\"children\":[{\"id\":\"6baf6df7-9a83-4ead-be65-4711f6a4f887\",\"type\":\"radio\",\"labelText\":\"Radio Button\"}]},{\"id\":\"f68f60d9-4538-4047-8343-504a927c8a66\",\"tabTitle\":\"tab-2\",\"children\":[{\"id\":\"43989c6a-1e8c-4e40-b02b-743f6e0d3533\",\"type\":\"textarea\",\"labelText\":\"Text Area\"}]}]},{\"id\":\"6d13daa4-da42-4d16-851d-2df2b00fc8af\",\"type\":\"button\",\"labelText\":\"Submit\"}]}",
            "diagram": {
              "x": 700,
              "y": 1000
            }
          },
          {
            "id": "SubEndNode_1",
            "type": "END",
            "name": "End",
            "diagram": {
              "x": 1700,
              "y": 1000
            }
          }
        ],
        "connectors": [
          {
            "source": "SubStartNode_1",
            "target": "SubProcess_1_FormNode_1",
            "condition": "{\"group\":{\"combinator\":\"and\",\"not\":false,\"rules\":[{\"rule\":{\"dataType\":\"String\",\"lhs\":\"PEM\",\"rhs\":\"PEM\",\"operator\":\"equals\"}}]}}"
          },
          {
            "source": "SubProcess_1_FormNode_1",
            "target": "SubProcess_1_apiNode",
            "condition": "{\"group\":{\"combinator\":\"and\",\"not\":false,\"rules\":[{\"rule\":{\"dataType\":\"String\",\"lhs\":\"PEM\",\"rhs\":\"PEM\",\"operator\":\"equals\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstName\",\"rhs\":\"PEM\",\"operator\":\"notEquals\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstName\",\"rhs\":\"PEM\",\"operator\":\"notStartsWith\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstNamePEM\",\"rhs\":\"PEM\",\"operator\":\"endsWith\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstName\",\"rhs\":\"PEM\",\"operator\":\"notEndsWith\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstNamePEM\",\"rhs\":\"PEM\",\"operator\":\"contains\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstName\",\"rhs\":\"PEM\",\"operator\":\"notContains\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstName\",\"rhs\":\"PEM\",\"operator\":\"isNotNull\"}},{\"rule\":{\"dataType\":\"String\",\"lhs\":\"FirstName\",\"rhs\":\"PEM\",\"operator\":\"isNotNull\"}},{\"group\":{\"combinator\":\"OR\",\"not\":true,\"rules\":[{\"group\":{\"combinator\":\"and\",\"not\":false,\"rules\":[{\"rule\":{\"dataType\":\"Boolean\",\"lhs\":\"true\",\"rhs\":\"true\",\"operator\":\"equals\"}},{\"rule\":{\"dataType\":\"Boolean\",\"lhs\":\"true\",\"rhs\":\"false\",\"operator\":\"notEquals\"}}]}}]}},{\"group\":{\"combinator\":\"and\",\"not\":false,\"rules\":[{\"rule\":{\"dataType\":\"Number\",\"lhs\":\"1\",\"rhs\":\"2\",\"operator\":\"lessThan\"}},{\"rule\":{\"dataType\":\"Number\",\"lhs\":\"2\",\"rhs\":\"1\",\"operator\":\"greaterThan\"}},{\"rule\":{\"dataType\":\"Number\",\"lhs\":\"1\",\"rhs\":\"1\",\"operator\":\"lessThanEquals\"}},{\"rule\":{\"dataType\":\"Number\",\"lhs\":\"2\",\"rhs\":\"2\",\"operator\":\"greaterThanEquals\"}},{\"rule\":{\"dataType\":\"Number\",\"lhs\":\"1\",\"rhs\":\"2\",\"operator\":\"notEquals\"}},{\"rule\":{\"dataType\":\"Number\",\"lhs\":\"1\",\"rhs\":\"1\",\"operator\":\"equals\"}}]}}]}}"
          },
          {
            "source": "SubProcess_1_apiNode",
            "target": "SubProcess_1_FormNode_2",
            "condition": "{\"group\":{\"combinator\":\"and\",\"not\":false,\"rules\":[{\"rule\":{\"dataType\":\"String\",\"lhs\":\"PEM\",\"rhs\":\"PEM\",\"operator\":\"equals\"}}]}}"
          },
          {
            "source": "SubProcess_1_FormNode_2",
            "target": "SubEndNode_1",
            "condition": "{\"group\":{\"combinator\":\"and\",\"not\":false,\"rules\":[{\"rule\":{\"dataType\":\"String\",\"lhs\":\"PEM\",\"rhs\":\"PEM\",\"operator\":\"equals\"}}]}}"
          }
        ],
        "diagram": {
          "x": 1000,
          "y": 200
        }
      },
      {
        "id": "SubProcess_2",
        "type": "SPONSOR",
        "name": "SPONSOR Sub Process Node",
        "description": "This process describes the order fulfilment workflow.",
        "userKeys": "user1,user2",
        "roleKeys": "group1",
        "showToPartner": false,
        "nodes": [
          {
            "id": "SubProcess_2_StartNode_1",
            "type": "START",
            "name": "Start",
            "diagram": {
              "x": 300,
              "y": 2000
            }
          },
          {
            "id": "SubProcess_2_xsltNode1",
            "name": "XSLT Node",
            "type": "XSLT",
            "description": "xsltNode- task",
            "loop": {
              "loopCardinality": 5,
              "completionCondition":"${nrOfCompletedInstances/nrOfInstances > 0.5}"
